Fix prospector issues
************* Module jsonschema2md
jsonschema2md/__init__.py:42:9: D401(ruff): First line of docstring should be in imperative mood: "Setup JSON Schema to Markdown parser." [See: https://docs.astral.sh/ruff/rules/non-imperative-mood]
jsonschema2md/__init__.py:66:48: error(mypy): Missing type parameters for generic type "dict"  [type-arg]
jsonschema2md/__init__.py:115:40: error(mypy): Missing type parameters for generic type "dict"  [type-arg]
jsonschema2md/__init__.py:116:9: error(mypy): Function is missing a type annotation  [no-untyped-def]
jsonschema2md/__init__.py:120:9: error(mypy): Function is missing a type annotation  [no-untyped-def]
jsonschema2md/__init__.py:139:31: error(mypy): Call to untyped function (unknown) in typed context  [no-untyped-call]
jsonschema2md/__init__.py:147:20: error(mypy): Missing type parameters for generic type "dict"  [type-arg]
jsonschema2md/__init__.py:147:26: error(mypy): Missing type parameters for generic type "list"  [type-arg]
jsonschema2md/__init__.py:244:21: B020(ruff): Loop control variable `property_name` overrides iterable it iterates [See: https://docs.astral.sh/ruff/rules/loop-variable-overrides-iterator]
jsonschema2md/__init__.py:259:43: error(mypy): Missing type parameters for generic type "dict"  [type-arg]
jsonschema2md/__init__.py:318:1: error(mypy): Function is missing a return type annotation  [no-untyped-def]
jsonschema2md/__init__.py:318:1: note(mypy): Use "-> None" if function does not return a value
jsonschema2md/__init__.py:357:5: error(mypy): Call to untyped function "main" in typed context  [no-untyped-call]